#!/usr/bin/env python3
"""Regenerates every platform's icon from the one source image, resources/icon.png.

    python resources/make_icon_header.py

Writes:
  resources/icon.ico  Windows. Several sizes in one file, embedded into the
                      .exe by resources/app.rc.
  src/app_icon.h      Linux. Raw RGBA pixels for glfwSetWindowIcon() in
                      main.cpp -- that call wants pixels, not an image file,
                      and this project has no image decoder, so the pixels
                      are baked into a header instead.

So to change the icon: replace resources/icon.png, run this once, rebuild.

Needs Python 3 + Pillow:  pip install pillow
(The filename is historical -- it started out generating only the header.)
"""
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("This script needs Pillow:  pip install pillow")

HERE = Path(__file__).resolve().parent
SRC = HERE / "icon.png"
ICO_OUT = HERE / "icon.ico"
HEADER_OUT = HERE.parent / "src" / "app_icon.h"

# Windows picks whichever size fits the place it's drawing (16 = title bar,
# 32/48 = taskbar and Explorer lists, 256 = large Explorer icons).
ICO_SIZES = [16, 24, 32, 48, 64, 128, 256]
# Linux window managers choose from these for the title bar / taskbar / alt-tab.
HEADER_SIZES = [32, 64, 128]

src = Image.open(SRC).convert("RGBA")
if src.width != src.height:
    sys.exit(f"{SRC.name} must be square, but it is {src.width}x{src.height}.")
if src.width < max(ICO_SIZES):
    # Pillow silently DROPS any .ico size larger than the source image, which
    # would leave Windows without its 256px icon and make large icons blurry.
    sys.exit(f"{SRC.name} is only {src.width}px wide; it needs to be at least "
             f"{max(ICO_SIZES)}px so every .ico size can be made from it.")

# --- Windows: icon.ico -------------------------------------------------------
src.save(ICO_OUT, format="ICO", sizes=[(s, s) for s in ICO_SIZES])
written = sorted(s[0] for s in Image.open(ICO_OUT).info["sizes"])
print(f"wrote {ICO_OUT.relative_to(HERE.parent)}  sizes: {written}")

# --- Linux: src/app_icon.h ---------------------------------------------------
lines = [
    "#pragma once",
    "// GENERATED by resources/make_icon_header.py from resources/icon.png -- do not edit by hand.",
    "// Raw RGBA pixels (4 bytes per pixel, row-major) for glfwSetWindowIcon().",
    "",
]
for size in HEADER_SIZES:
    data = src.resize((size, size), Image.LANCZOS).tobytes()
    lines.append(f"static const int kAppIcon{size}Size = {size};")
    lines.append(f"static const unsigned char kAppIcon{size}[{len(data)}] = {{")
    for i in range(0, len(data), 24):
        lines.append("    " + ",".join(str(b) for b in data[i:i + 24]) + ",")
    lines.append("};")
    lines.append("")
HEADER_OUT.write_text("\n".join(lines))
print(f"wrote {HEADER_OUT.relative_to(HERE.parent)}  sizes: {HEADER_SIZES}  "
      f"({HEADER_OUT.stat().st_size // 1024} KB)")
